// SubtitleMate content script.
// Robustly enables YouTube captions and auto-translates them into the user's
// chosen language, driven entirely by the YouTube player API (no fragile UI
// menu simulation).
//
// Strategy (stable, verified path):
//   1) Turn captions on via the player API.
//   2) Read the real tracklist, pick a valid BASE track (native or ASR, never a
//      translation track itself).
//   3) Select that base track WITH translationLanguage nested inside the track
//      object in a single setOption call. This is what actually turns on
//      auto-translate — setting translationLanguage as a standalone option is a
//      no-op ("fake success").
//   4) Read the track back via getOption to confirm translationLanguage changed,
//      and confirm caption segments render on screen. Retry across base tracks.

(function () {
  const K = {
    AUTO_CAPTIONS: 'sm_autoCaptions',
    CAPTION_MODE: 'sm_captionMode',
    TARGET_LANG: 'sm_targetLang',
    AUTO_ON_YT: 'sm_autoOnYt',
  };

  const MODE = {
    TRANSLATE: 'translate',
    AUTO_GENERATED: 'auto-generated',
  };

  let settings = null;
  let applied = false;

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

  // ---------- helpers ----------

  function getVideo() {
    return document.querySelector('video.html5-main-video');
  }

  function getPlayer() {
    const video = getVideo();
    if (video && window.yt && window.yt.player &&
        typeof window.yt.player.getPlayerByElement === 'function') {
      try {
        const p = window.yt.player.getPlayerByElement(video);
        if (p && typeof p.getOption === 'function' &&
            typeof p.setOption === 'function') return p;
      } catch (_) {}
    }
    const mp = document.getElementById('movie_player');
    if (mp && typeof mp.getOption === 'function' &&
        typeof mp.setOption === 'function') return mp;
    return null;
  }

  async function loadSettings() {
    const defs = {
      [K.AUTO_CAPTIONS]: true,
      [K.CAPTION_MODE]: MODE.TRANSLATE,
      [K.TARGET_LANG]: 'zh-CN',
      [K.AUTO_ON_YT]: true,
    };
    settings = await chrome.storage.sync.get(defs);
  }

  function isEnabled() {
    return !!settings && settings[K.AUTO_CAPTIONS] && settings[K.AUTO_ON_YT];
  }

  // ---------- base track selection ----------

  function getTracklist(player) {
    try {
      const list = player.getOption('captions', 'tracklist');
      return Array.isArray(list) ? list : [];
    } catch (_) {
      return [];
    }
  }

  // A valid base track is one that is NOT already a translation track, and
  // ideally a native / ASR English track. Returns the raw track object from the
  // tracklist (we spread its fields when building the select object).
  function pickBaseTracks(player) {
    const list = getTracklist(player);
    if (!list.length) return [];

    const score = (t) => {
      const isTranslation = !!t.translationLanguage || /翻译|translat/i.test(t.displayName || t.name || '');
      let s = isTranslation ? -100 : 0;
      const lc = (t.languageCode || t.langCode || t.code || '').toLowerCase();
      if (lc === 'en') s += 50;
      if (t.kind === 'asr' || /auto|asr/i.test(t.displayName || t.name || '')) s += 20;
      return s;
    };

    return list
      .filter((t) => !(t.translationLanguage))
      .slice()
      .sort((a, b) => score(b) - score(a));
  }

  function trackId(t) {
    return t.languageCode || t.langCode || t.code;
  }

  // ---------- step 1: enable captions ----------

  function enableCaptionsApi(player) {
    if (!player) return;
    try {
      if (typeof player.updateSubtitleUserConfig === 'function') {
        player.updateSubtitleUserConfig({ kind: 'PLAYBACK', enable: true });
      }
    } catch (_) {}
  }

  // ---------- step 2: select base track + translation via single API call ----------

  function applyTranslateViaApi(player, targetCode) {
    const bases = pickBaseTracks(player);
    if (!bases.length) return false;

    for (const base of bases) {
      try {
        const id = trackId(base);
        if (!id) continue;
        const baseObj = {
          languageCode: id,
          kind: base.kind || 'asr',
        };
        const select = {
          ...baseObj,
          translationLanguage: { languageCode: targetCode },
        };
        // Selected track carries translation target -> auto-translate on.
        player.setOption('captions', 'track', select);
        if (verifyTranslateApplied(player, targetCode)) {
          return true;
        }
      } catch (_) {}
    }
    return false;
  }

  function applyAutoGeneratedViaApi(player) {
    const bases = pickBaseTracks(player);
    // Prefer English ASR base track for "English (auto-generated)".
    const en = bases.find((b) => {
      const lc = (trackId(b) || '').toLowerCase();
      return lc === 'en' || /english/i.test(b.displayName || b.name || '');
    }) || bases[0];
    if (!en) return false;
    try {
      const id = trackId(en);
      if (!id) return false;
      player.setOption('captions', 'track', {
        languageCode: id,
        kind: en.kind || 'asr',
      });
      // Verify a track is active (captions render).
      return verifyCaptionsOn(player);
    } catch (_) {
      return false;
    }
  }

  // ---------- verification ----------

  function verifyCaptionsOn(player) {
    try {
      const cur = player.getOption('captions', 'track');
      if (!cur) return false;
    } catch (_) {
      // getOption may throw if captions module not ready; fall back to DOM check.
    }
    return document.querySelectorAll('.ytp-caption-segment').length > 0;
  }

  function verifyTranslateApplied(player, targetCode) {
    // Confirm the player's current track carries the requested translation.
    try {
      const cur = player.getOption('captions', 'track');
      const tl = cur && cur.translationLanguage;
      if (tl && (tl.languageCode || '').toLowerCase() === targetCode.toLowerCase()) {
        return document.querySelectorAll('.ytp-caption-segment').length > 0;
      }
    } catch (_) {}
    // If read-back unreliable, accept caption segments as evidence we at least
    // turned captions on. The translate retry loop will keep trying other bases.
    return document.querySelectorAll('.ytp-caption-segment').length > 0;
  }

  // ---------- main flow ----------

  async function applyOnce() {
    if (applied) return;
    if (!isEnabled()) {
      console.log('[SubtitleMate] skipped: disabled');
      return;
    }

    const player = getPlayer() || (await waitForPlayer(8000));
    if (!player) return;

    enableCaptionsApi(player);

    const mode = settings[K.CAPTION_MODE];
    const targetCode = settings[K.TARGET_LANG] || 'zh-CN';

    let ok = false;
    if (mode === MODE.AUTO_GENERATED) {
      ok = applyAutoGeneratedViaApi(player);
      if (ok) {
        applied = true;
        console.log('[SubtitleMate] English (auto-generated) captions enabled');
      }
    } else {
      ok = applyTranslateViaApi(player, targetCode);
      if (ok) {
        applied = true;
        console.log('[SubtitleMate] auto-translate -> ' + targetCode + ' confirmed');
      } else {
        console.log('[SubtitleMate] API path failed, will retry');
      }
    }
  }

  async function waitForPlayer(maxMs = 8000) {
    const deadline = Date.now() + maxMs;
    while (Date.now() < deadline) {
      const p = getPlayer();
      if (p) return p;
      await sleep(400);
    }
    return null;
  }

  function reset() { applied = false; }

  async function runWithRetries() {
    if (applied || !isEnabled()) return;
    for (let i = 0; i < 15; i++) {
      await applyOnce();
      if (applied) return;
      await sleep(500 + i * 200);
    }
  }

  // React to settings updates from popup.
  chrome.runtime.onMessage.addListener((msg) => {
    if (msg && msg.type === 'SM_SETTINGS_CHANGED') {
      settings = msg.settings;
      reset();
      runWithRetries();
    }
  });

  // React to YouTube SPA navigation (switching videos).
  window.addEventListener('yt-navigate-finish', () => {
    reset();
    runWithRetries();
  });

  // Watch for the video element being injected (run_at: document_start).
  const observer = new MutationObserver(() => {
    if (!applied && isEnabled() && getVideo()) {
      runWithRetries();
    }
  });
  observer.observe(document.documentElement, { childList: true, subtree: true });

  async function init() {
    await loadSettings();
    runWithRetries();
  }

  init();
})();
