// Shared module: i18n dictionary + storage key constants + storage helpers.
// Loaded as a classic script in popup.html (and referenced for key names in content.js).

(function () {
  const STORAGE_KEYS = {
    AUTO_CAPTIONS: 'sm_autoCaptions',
    CAPTION_MODE: 'sm_captionMode',
    TARGET_LANG: 'sm_targetLang',
    AUTO_ON_YT: 'sm_autoOnYt',
    AUTO_PLAYBACK_SPEED: 'sm_autoPlaybackSpeed',
    PLAYBACK_RATE: 'sm_playbackRate',
    UI_LANG: 'sm_uiLang',
  };

  // Allowed playback rate values (matches YouTube's speed menu).
  const PLAYBACK_RATES = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.5, 3];

  // Caption modes:
  //  'translate'      -> turn captions on and auto-translate into TARGET_LANG
  //  'auto-generated' -> turn captions on and pick "English (auto-generated)"
  const CAPTION_MODES = {
    TRANSLATE: 'translate',
    AUTO_GENERATED: 'auto-generated',
  };

  const LANGUAGES = [
    { code: 'en', en: 'English', zh: '英语' },
    { code: 'zh-CN', en: 'Chinese (Simplified)', zh: '中文（简体）' },
    { code: 'zh-TW', en: 'Chinese (Traditional)', zh: '中文（繁体）' },
    { code: 'ja', en: 'Japanese', zh: '日语' },
    { code: 'ko', en: 'Korean', zh: '韩语' },
    { code: 'fr', en: 'French', zh: '法语' },
    { code: 'de', en: 'German', zh: '德语' },
    { code: 'es', en: 'Spanish', zh: '西班牙语' },
    { code: 'pt', en: 'Portuguese', zh: '葡萄牙语' },
    { code: 'ru', en: 'Russian', zh: '俄语' },
    { code: 'it', en: 'Italian', zh: '意大利语' },
    { code: 'ar', en: 'Arabic', zh: '阿拉伯语' },
    { code: 'hi', en: 'Hindi', zh: '印地语' },
    { code: 'th', en: 'Thai', zh: '泰语' },
    { code: 'vi', en: 'Vietnamese', zh: '越南语' },
  ];

  // UI-only copy. We keep popup text dynamic by language so it can be switched.
  const I18N = {
    en: {
      name: 'SubtitleMate',
      autoCaptions: 'Auto-enable captions',
      captionMode: 'Caption mode',
      modeTranslate: 'Auto-translate',
      modeAutoGenerated: 'English (auto-generated)',
      targetLang: 'Translate to',
      targetLangHint: 'Used when caption mode is "Auto-translate"',
      autoOnYt: 'Enable automatically on YouTube',
      autoPlaybackSpeed: 'Auto-set playback speed',
      playbackSpeed: 'Playback speed',
      settings: 'Settings',
      applySettings: 'Apply to current video',
      applyNow: 'Apply',
      applyTriggered: 'Applying…',
      on: 'ON', off: 'OFF',
      saved: 'Saved',
      supportLink: 'Support the developer',
    },
    zh: {
      name: 'SubtitleMate',
      autoCaptions: '自动开启字幕',
      captionMode: '字幕模式',
      modeTranslate: '自动翻译',
      modeAutoGenerated: '英语（自动生成）',
      targetLang: '翻译为',
      targetLangHint: '仅在「自动翻译」模式下生效',
      autoOnYt: '在 YouTube 上自动启用',
      autoPlaybackSpeed: '自动设置播放速度',
      playbackSpeed: '播放速度',
      settings: '设置',
      applySettings: '应用到当前视频',
      applyNow: '应用',
      applyTriggered: '正在应用…',
      on: '开', off: '关',
      saved: '已保存',
      supportLink: '支持开发者',
    },
  };

  const DEFAULTS = {
    [STORAGE_KEYS.AUTO_CAPTIONS]: true,
    [STORAGE_KEYS.CAPTION_MODE]: CAPTION_MODES.TRANSLATE,
    [STORAGE_KEYS.TARGET_LANG]: 'zh-CN',
    [STORAGE_KEYS.AUTO_ON_YT]: true,
    [STORAGE_KEYS.AUTO_PLAYBACK_SPEED]: false,
    [STORAGE_KEYS.PLAYBACK_RATE]: 1.5,
    [STORAGE_KEYS.UI_LANG]: 'en',
  };

  async function getSettings() {
    const data = await chrome.storage.sync.get(DEFAULTS);
    const out = {};
    for (const k of Object.keys(DEFAULTS)) out[k] = data[k];
    return out;
  }

  async function setSettings(patch) {
    await chrome.storage.sync.set(patch);
  }

  function getCurrentUiLang() {
    const stored = localStorage.getItem('sm_uiLang');
    if (stored === 'en' || stored === 'zh') return stored;
    const nav = (navigator.language || 'en').toLowerCase();
    return nav.startsWith('zh') ? 'zh' : 'en';
  }

  function setCurrentUiLang(lang) {
    localStorage.setItem('sm_uiLang', lang);
    try {
      chrome.storage.sync.set({ [STORAGE_KEYS.UI_LANG]: lang });
    } catch (e) {}
  }

  if (typeof window !== 'undefined') {
    window.SM = { STORAGE_KEYS, LANGUAGES, CAPTION_MODES, I18N, DEFAULTS, getSettings, setSettings, getCurrentUiLang, setCurrentUiLang };
  }
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { STORAGE_KEYS, LANGUAGES, CAPTION_MODES, I18N, DEFAULTS, getSettings, setSettings };
  }
})();
