(function () {
  const { STORAGE_KEYS, LANGUAGES, CAPTION_MODES, I18N, getSettings, setSettings, getCurrentUiLang, setCurrentUiLang } = window.SM;

  let uiLang = getCurrentUiLang();
  let settings = null;

  const $ = (id) => document.getElementById(id);

  function t(key) { return I18N[uiLang][key]; }

  function fillLangOptions(select, selectedCode) {
    select.innerHTML = '';
    for (const lang of LANGUAGES) {
      const opt = document.createElement('option');
      opt.value = lang.code;
      opt.textContent = uiLang === 'zh' ? lang.zh : lang.en;
      if (lang.code === selectedCode) opt.selected = true;
      select.appendChild(opt);
    }
  }

  function fillModeOptions(select, selected) {
    select.innerHTML = '';
    const modes = [
      { value: CAPTION_MODES.TRANSLATE, label: I18N[uiLang].modeTranslate },
      { value: CAPTION_MODES.AUTO_GENERATED, label: I18N[uiLang].modeAutoGenerated },
    ];
    for (const m of modes) {
      const opt = document.createElement('option');
      opt.value = m.value;
      opt.textContent = m.label;
      if (m.value === selected) opt.selected = true;
      select.appendChild(opt);
    }
  }

  function applyUI() {
    const i18n = I18N[uiLang];
    $('extName').textContent = i18n.name;
    $('lblAutoCaptions').textContent = i18n.autoCaptions;
    $('lblCaptionMode').textContent = i18n.captionMode;
    $('lblTargetLang').textContent = i18n.targetLang;
    $('lblTargetLangHint').textContent = i18n.targetLangHint;
    $('lblRemember').textContent = i18n.remember;
    $('lblAutoYt').textContent = i18n.autoOnYt;
    $('btnApplyText').textContent = i18n.applyNow;
    $('btnApply').title = i18n.applySettings;
    document.documentElement.lang = uiLang === 'zh' ? 'zh-CN' : 'en';

    const toggle = $('toggleAuto');
    toggle.setAttribute('aria-checked', String(settings[STORAGE_KEYS.AUTO_CAPTIONS]));

    fillModeOptions($('captionMode'), settings[STORAGE_KEYS.CAPTION_MODE]);
    fillLangOptions($('targetLang'), settings[STORAGE_KEYS.TARGET_LANG]);
    // Target language only applies in auto-translate mode.
    const translateMode = settings[STORAGE_KEYS.CAPTION_MODE] === CAPTION_MODES.TRANSLATE;
    $('targetLang').disabled = !translateMode;
    $('targetLang').classList.toggle('disabled', !translateMode);
    $('lblTargetLangHint').style.visibility = translateMode ? 'visible' : 'hidden';
    $('chkRemember').checked = settings[STORAGE_KEYS.REMEMBER_LANG];
    $('chkAutoYt').checked = settings[STORAGE_KEYS.AUTO_ON_YT];
  }

  async function save(patch) {
    Object.assign(settings, patch);
    await setSettings(patch);
    const hint = $('savedHint');
    hint.textContent = t('saved');
    hint.classList.add('show');
    setTimeout(() => hint.classList.remove('show'), 1400);
    // Notify content scripts about the change.
    chrome.runtime.sendMessage({ type: 'SM_SETTINGS_CHANGED', settings }).catch(() => {});
  }

  function bindEvents() {
    $('toggleAuto').addEventListener('click', () => {
      const next = !settings[STORAGE_KEYS.AUTO_CAPTIONS];
      save({ [STORAGE_KEYS.AUTO_CAPTIONS]: next });
      applyUI();
    });

    $('captionMode').addEventListener('change', (e) => {
      save({ [STORAGE_KEYS.CAPTION_MODE]: e.target.value });
      applyUI();
    });

    $('targetLang').addEventListener('change', (e) =>
      save({ [STORAGE_KEYS.TARGET_LANG]: e.target.value }));

    $('chkRemember').addEventListener('change', (e) =>
      save({ [STORAGE_KEYS.REMEMBER_LANG]: e.target.checked }));

    $('chkAutoYt').addEventListener('change', (e) =>
      save({ [STORAGE_KEYS.AUTO_ON_YT]: e.target.checked }));

    $('langSwitch').addEventListener('click', () => {
      uiLang = uiLang === 'en' ? 'zh' : 'en';
      setCurrentUiLang(uiLang);
      applyUI();
    });

    $('btnApply').addEventListener('click', () => {
      const btn = $('btnApply');
      if (btn.classList.contains('loading')) return;
      btn.classList.add('loading');
      const original = I18N[uiLang].applyNow;
      $('btnApplyText').textContent = t('applyTriggered');
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        const tab = tabs && tabs[0];
        if (!tab || !tab.id) return;
        chrome.tabs.sendMessage(tab.id, { type: 'SM_APPLY_SUBTITLES' }).catch(() => {});
      });
      setTimeout(() => {
        $('btnApplyText').textContent = original;
        btn.classList.remove('loading');
      }, 1400);
    });
  }

  async function init() {
    settings = await getSettings();
    $('logo').src = chrome.runtime.getURL('icons/icon48.png');
    bindEvents();
    applyUI();
  }

  init();
})();
